Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace Tema_2.Models
{
    public class Appointment
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        public DateTime date { get; set; }
        public string clientName { get; set; }
        public string phone { get; set; }
        public string car { get; set; }
        public string problem { get; set; }
        public int status { get; set; }
        
    }
}

Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tema_2.DAL;
using Tema_2.Data;
using Tema_2.Models;

namespace Tema_2.Controllers
{
    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly Tema_2Context _context;

        //modificari
        /*private IAppointmentRepository appRepos;

        public AppointmentsController(Tema_2Context context)
        {
            this.appRepos = new AppointmentRepository(context);
        }*/
        //

        public AppointmentsController(Tema_2Context context)
        {
            _context = context;
        }

        // GET: Appointments
        /*public async Task<IActionResult> Index()
        {
            return View(await _context.Appointment.ToListAsync());
        }*/
        public async Task<IActionResult> Index(string searchString1, string searchString2)
        {
            var apps = from m in _context.Appointment
                         select m;
            //modificare
            //var apps = from m in appRepos.GetApps()
            //           select m;

            if (!String.IsNullOrEmpty(searchString1) && !String.IsNullOrEmpty(searchString2))
            {
                //apps = apps.Where(s => s.date.ToString().Contains(searchString1));
                apps = apps.Where(s => s.date > DateTime.Parse(searchString1) && s.date < DateTime.Parse(searchString2));
            }
            else 
            {
                if (!String.IsNullOrEmpty(searchString1))
                {
                    apps = apps.Where(s => s.date > DateTime.Parse(searchString1));
                }
                else
                {
                    if (!String.IsNullOrEmpty(searchString2))
                    {
                        apps = apps.Where(s => s.date < DateTime.Parse(searchString2));
                    }
                }
            }

            return View(await apps.ToListAsync());
            //modificare
            //return View(await apps.AsQueryable().ToListAsync());

        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

            //modificare
        /*public ViewResult Details(int id)
        {
            Appointment app = appRepos.GetAppByID(id);
            return View(app);
        }*/
        //

        // GET: Appointments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,date,clientName,phone,car,problem,status")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                 _context.Add(appointment);
                 await _context.SaveChangesAsync();
                 //modificare
                //appRepos.InsertApp(appointment);
                //appRepos.Save();
                //
                return RedirectToAction(nameof(Index));
            }
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }
        //modifcare
        /*public ActionResult Edit(int id)
        {
            Appointment app = appRepos.GetAppByID(id);
            return View(app);
        }*/
        //

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,date,clientName,phone,car,problem,status")] Appointment appointment)
        {
            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                    //modificare
                    //appRepos.UpdateApp(appointment);
                    //appRepos.Save();
                    //
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }
        //modifcare
        /*public ActionResult Delete(bool? saveChangesError = false, int id = 0)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Appointment app = appRepos.GetAppByID(id);
            return View(app);
        }*/
        //

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appointment = await _context.Appointment.FindAsync(id);
            _context.Appointment.Remove(appointment);
            await _context.SaveChangesAsync();
            //modifcare
            //Appointment app = appRepos.GetAppByID(id);
            //appRepos.DeleteApp(id);
            //appRepos.Save();
            //
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return _context.Appointment.Any(e => e.Id == id);
            //modifcare
            //return appRepos.GetAppByID(id) != null;
            //
        }
    }
}

Views/Appointments/Create.cshtml
@model Tema_2.Models.Appointment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="clientName" class="control-label"></label>
                <input asp-for="clientName" class="form-control" />
                <span asp-validation-for="clientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="car" class="control-label"></label>
                <input asp-for="car" class="form-control" />
                <span asp-validation-for="car" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="problem" class="control-label"></label>
                <input asp-for="problem" class="form-control" />
                <span asp-validation-for="problem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Appointments/Delete.cshtml
@model Tema_2.Models.Appointment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.clientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.clientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.car)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.problem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.problem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Appointments/Details.cshtml
@model Tema_2.Models.Appointment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.clientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.clientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.car)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.problem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.problem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Appointments/Edit.cshtml
@model Tema_2.Models.Appointment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date" class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="clientName" class="control-label"></label>
                <input asp-for="clientName" class="form-control" />
                <span asp-validation-for="clientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="car" class="control-label"></label>
                <input asp-for="car" class="form-control" />
                <span asp-validation-for="car" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="problem" class="control-label"></label>
                <input asp-for="problem" class="form-control" />
                <span asp-validation-for="problem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Appointments/Index.cshtml
@model IEnumerable<Tema_2.Models.Appointment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Appointments" asp-action="Index" method="get">
    <p>
        Start date: <input type="date" name="SearchString1">
        End date: <input type="date" name="SearchString2">
        <input type="submit" value="Generate report" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.clientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.car)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.problem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.clientName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.car)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.problem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>